### ISSUE TITLE
Add mpi4py to the conda dependency list

### ISSUE THREAD

**Issue by xiki-tempula** [choderalab/mpiplus#7]
mpi4py is a dependency for openmmtools but is not listed in the conda dependency list

**Comment by ijpulidos** [comment]
@xiki-tempula Thanks for the report, you are correct, `mpi4py` should be installed if we want to use multiple MPI processes.

I believe the issue is really on https://github.com/choderalab/mpiplus/ since that one is the one using `mpi4py` directly. I'm going to transfer the issue to that repo.

**Comment by ijpulidos** [comment]
Should be fixed once https://github.com/conda-forge/mpiplus-feedstock/pull/11 is merged and new packages for `mpiplus` are generated.

**Comment by mikemhenry** [comment]
So that didn't fix it since it only added a testing requirement. Instead of adding it as a dep (which could cause issues) I will improve the logic to check the envars + if mpy4py exists https://github.com/choderalab/mpiplus/blob/216f1328d40f71e6554d909d470b6fe3104fde68/mpiplus/mpiplus.py#L102-L119
